# Generated by Django 3.2.3 on 2021-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_registered',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
